
[[constraint]]
  name = "github.com/chzyer/readline"
  version = "1.4.0"

[[constraint]]
  branch = "release-branch.go1.8"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/elazarl/go-bindata-assetfs"
  version = "1.0.0"
